apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deployment
  labels:
    app: todo-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo-label
  template:
    metadata:
      labels:
        app: todo-label
    spec:
      containers:
      - name: todo-ctr
        image: trainwithshubham/node-app-test-new
        ports:
        - containerPort: 8000
---

apiVersion: v1
kind: Service
metadata:
  name: todo-service
spec:
  selector:
    app : todo-label
  type: NodePort    
  ports:
    - port: 80
      targetPort: 8000
      nodePort: 30087  
